#!/bin/bash
CYAN='\033[0;36m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
echo ""
echo -e "${CYAN}     ▄██▄            __  __            _      ___ ___ ${NC}"
echo -e "${CYAN}   ▄██████▄         |  \/  | __ _ _ __| | __ |_ _|_ _|${NC}"
echo -e "${CYAN}  ▄████▀▀████▄      | |\/| |/ _\` | '__| |/ /  | | | | ${NC}"
echo -e "${CYAN} ▄█████    █████▄   | |  | | (_| | |  |   <   | | | | ${NC}"
echo -e "${CYAN}▄██████▄  ▄██████▄  |_|  |_|\__,_|_|  |_|\_\ |___|___|${NC}"
echo -e "${CYAN}████████  ██▀  ▀██      _            _     _   ${NC}"
echo -e "${CYAN}███▀▀███  ██   ▄██     / \   ___ ___(_)___| |_ ${NC}"
echo -e "${CYAN}██    ██  ▀ ▄█████    / _ \ / __/ __| / __| __|${NC}"
echo -e "${CYAN}███▄▄ ▀█  ▄███████   / ___ \\__ \__ \ \__ \ |_ ${NC}"
echo -e "${CYAN}▀█████▄   ███████▀  /_/   \_\___/___/_|___/\__|${NC}"
echo ""
echo -e "${BLUE}  Mycroft Mark II — Home Assistant Voice Satellite${NC}"
echo -e "${BLUE}  github.com/andlo/mark2-assist${NC}"
echo ""
echo -e "  ${CYAN}——  Installer  ——${NC}"
echo ""
echo -e "${GREEN}  System:${NC}"
printf "  %-12s %s\n" "Hostname:" "$(hostname)"
printf "  %-12s %s\n" "Uptime:"   "$(uptime -p | sed 's/up //')"
printf "  %-12s %s\n" "IP:"       "$(hostname -I | awk '{print $1}')"
echo ""
echo -e "${GREEN}  Services:${NC}"
printf "  ${GREEN}✓${NC} %-28s %s\n" "Voice assistant (LVA)" "running"
printf "  ${GREEN}✓${NC} %-28s %s\n" "XVF3510 audio init" "done (oneshot)"
printf "  ${YELLOW}✗${NC} %-28s %s\n" "Face animation" "inactive"
printf "  ${GREEN}✓${NC} %-28s %s\n" "PipeWire/WirePlumber" "running"
echo ""
echo -e "  ${CYAN}Docs:${NC} github.com/andlo/mark2-assist"
echo -e "  ${CYAN}Logs:${NC} journalctl --user -u lva -f"
echo ""
